INSERT INTO USER_TABLE(ID, USER_NAME, BIRTH_DATE, COUNTRY_OF_RESIDENCE, PHONE_NUMBER, GENDER) 
VALUES (NEXT VALUE FOR HIEM_SEQUENCE, 'George', '1920-10-14', 'France', '06085551023', 'Male');

INSERT INTO USER_TABLE(ID, USER_NAME, BIRTH_DATE, COUNTRY_OF_RESIDENCE, PHONE_NUMBER, GENDER) 
VALUES (NEXT VALUE FOR HIEM_SEQUENCE, 'Franklin', '1930-01-26', 'Massachusett', '06085551023', 'Male');